application: sage-math-inc
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "10m" # default is 10m, set this to 1d if happy

# static handlers can have their individual expiration times (if necessary)
handlers:
- url: /static
  static_dir: static
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /font
  static_dir: font
- url: /images
  static_dir: images

# main entrance point, everything is routed through smc.app
- url: /.*
  script: smc.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: markupsafe
  version: latest
- name: yaml
  version: latest

# a lot is activated by default, everything should be safe to use
pagespeed:
  enabled_rewriters:
  - CollapseWhitespace
  - ImageAddDimensions
  - RemoveComments
  - InlineImages
  - InlineJs
  - MinifyCss
  - CombineJs
  - JsOptimize
  - CombineCss

